config/routes.rb
SampleApp::Application.routes.draw do

  get "users/new"

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/about', :to => 'pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@titre = "Accueil"
  end

  def contact
  	@titre = "Contact"
  end

  def about
  	@titre = "A propos"
  end

  def help
  	@titre = "Aide"
  end

  def new
  	@titre = "Inscription"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def titre
		base_titre = "Simple App Ruby On Rails"
		if @titre.nil?
			base_titre
		else
			"#{base_titre} | #{@titre}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "Accueil", root_path %></li>
			<li><%= link_to "Aide", help_path %></li>
			<li><%= link_to "Login", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
		<%= image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
		<nav class="round">
			<ul>
				<li><%= link_to "Accueil", root_path %></li>
				<li><%= link_to "Aide", help_path %></li>
				<li><%= link_to "Login", '#' %></li>
			</ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
	<%= stylesheet_link_tag 'blueprint/screen.css', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print.css', :media => 'print' %>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> <%= titre %> </title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
	<%= render 'layouts/header' %>
	<section class="round">
		<%= yield %>
	</section>
	<%= render 'layouts/footer' %>
</div>
</body>

</html>

app/views/pages/about.html.erb
<h1>Simple App</h1>
<p>Exemple de page about pour une application</p>

app/views/pages/contact.html.erb
<h1>Simple App</h1>
<p>Exemple de page contact pour une application</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
Obtenez de l'aide sur ce tutoriel, ou pas.. Parce que j'ai plutot la flemme de recopier ce qui est écrit dans le tuto !
</p>

app/views/pages/home.html.erb
<h1>Simple App</h1>
<p>Exemple de page accueil pour une application</p>
<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>